kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "enonic-site.chart" . }}
data:
  com.enonic.xp.app.main.cfg: |
    tourDisabled = True
  {{- if .Values.mail.enabled }}
  com.enonic.xp.mail.cfg: |
    smtpHost={{ .Release.Name }}-mail
    smtpPort=25
    smtpAuth=false
    smtpTLS=false
  {{- end }}
  com.enonic.xp.web.vhost.cfg: |
    enabled = true

    mapping.admin.host = {{ .Values.external_name }}
    mapping.admin.source = /admin
    mapping.admin.target = /admin
    mapping.admin.userStore = system

    mapping.api.host = localhost
    mapping.api.source = /api
    mapping.api.target = /api
    mapping.api.userStore = system

    mapping.status.host = localhost
    mapping.status.source = /status
    mapping.status.target = /status

    {{- range .Values.site_mappings }}

    mapping.{{ .name }}.host = {{ .host }}
    mapping.{{ .name }}.source = {{ .source }}
    mapping.{{ .name }}.target = {{ .target }}
    {{ if .user_store }}mapping.{{ .name }}.userStore = {{ .user_store }}{{ end }}
    {{- end }}
  {{- if .Values.su_password }}
  system.properties: |
    xp.suPassword = {{ .Values.su_password }}
  {{- end }}
  {{- if .Values.auth_file.enabled }}
  {{ .Values.auth_file.name }}: |
  {{- range $key, $val := .Values.auth_file.lines }}
    {{ $key }} = {{ $val }}
  {{- end }}
  {{- end }}
