apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "enonic-site.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.group_id }}
      securityContext:
        fsGroup: {{ .Values.group_id }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image | quote}}
        volumeMounts:
        - name: config
          mountPath: /enonic-xp/home/config
        - name: repo
          mountPath: /enonic-xp/home/repo
        - name: snapshots
          mountPath: /enonic-xp/home/snapshots
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status/server
            port: http
            httpHeaders:
            - name: Host
              value: localhost
        readinessProbe:
          initialDelaySeconds: 15
          httpGet:
            path: /status/server
            port: http
            httpHeaders:
            - name: Host
              value: localhost
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
      {{- if .Values.persistence.enabled }}
      - name: repo
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-repo
      - name: snapshots
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshots
      {{- else }}
      - name: repo
        emptyDir: {}
      - name: snapshots
        emptyDir: {}
      {{- end }}

